#ifndef AIBIOS_MODEL_WEIGHTS_H
#define AIBIOS_MODEL_WEIGHTS_H

#include <Uefi.h>

// MOCK WEIGHTS FOR FAST COMPILATION
STATIC CONST UINT8 gModelWeights[1048576] = {
  0
};

#endif // AIBIOS_MODEL_WEIGHTS_H
